//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://dohome.co.th/POSOutbound/RT")]
[System.Xml.Serialization.XmlRootAttribute("MT_RTI001_SALESTRANSACTION", Namespace="https://dohome.co.th/POSOutbound/RT", IsNullable=false)]
public partial class DT_RTI001_SALESTRANSACTION {
    
    private DT_RTI001_POSDW_TRANSACTION_INT[] pOSDW_TRANSACTION_INTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("POSDW_TRANSACTION_INT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_RTI001_POSDW_TRANSACTION_INT[] POSDW_TRANSACTION_INT {
        get {
            return this.pOSDW_TRANSACTION_INTField;
        }
        set {
            this.pOSDW_TRANSACTION_INTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://dohome.co.th/POSOutbound/RT")]
public partial class DT_RTI001_POSDW_TRANSACTION_INT {
    
    private string rETAILSTOREIDField;
    
    private string bUSINESSDAYDATEField;
    
    private string tRANSACTIONTYPECODEField;
    
    private string wORKSTATIONIDField;
    
    private string tRANSACTIONSEQUENCENUMBERField;
    
    private string bEGINDATETIMESTAMPField;
    
    private string eNDDATETIMESTAMPField;
    
    private string dEPARTMENTField;
    
    private string oPERATORQUALIFIERField;
    
    private string oPERATORIDField;
    
    private string tRANSACTIONCURRENCYField;
    
    private string pARTNERQUALIFIERField;
    
    private string pARTNERIDField;
    
    private DT_RTI001_POSDW_RETAILLINEITEM[] rETAILLINEITEMField;
    
    private DT_RTI001_POSDW_DISCOUNT[] dISCOUNTField;
    
    private DT_RTI001_POSDW_TENDER[] tENDERField;
    
    private DT_RTI001_POSDW_FINANCIALMOVEMENT[] fINANCIALMOVEMENTField;
    
    private string[] aDVPAYMENTSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RETAILSTOREID {
        get {
            return this.rETAILSTOREIDField;
        }
        set {
            this.rETAILSTOREIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BUSINESSDAYDATE {
        get {
            return this.bUSINESSDAYDATEField;
        }
        set {
            this.bUSINESSDAYDATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANSACTIONTYPECODE {
        get {
            return this.tRANSACTIONTYPECODEField;
        }
        set {
            this.tRANSACTIONTYPECODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WORKSTATIONID {
        get {
            return this.wORKSTATIONIDField;
        }
        set {
            this.wORKSTATIONIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANSACTIONSEQUENCENUMBER {
        get {
            return this.tRANSACTIONSEQUENCENUMBERField;
        }
        set {
            this.tRANSACTIONSEQUENCENUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BEGINDATETIMESTAMP {
        get {
            return this.bEGINDATETIMESTAMPField;
        }
        set {
            this.bEGINDATETIMESTAMPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ENDDATETIMESTAMP {
        get {
            return this.eNDDATETIMESTAMPField;
        }
        set {
            this.eNDDATETIMESTAMPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DEPARTMENT {
        get {
            return this.dEPARTMENTField;
        }
        set {
            this.dEPARTMENTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OPERATORQUALIFIER {
        get {
            return this.oPERATORQUALIFIERField;
        }
        set {
            this.oPERATORQUALIFIERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OPERATORID {
        get {
            return this.oPERATORIDField;
        }
        set {
            this.oPERATORIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANSACTIONCURRENCY {
        get {
            return this.tRANSACTIONCURRENCYField;
        }
        set {
            this.tRANSACTIONCURRENCYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PARTNERQUALIFIER {
        get {
            return this.pARTNERQUALIFIERField;
        }
        set {
            this.pARTNERQUALIFIERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PARTNERID {
        get {
            return this.pARTNERIDField;
        }
        set {
            this.pARTNERIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RETAILLINEITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_RTI001_POSDW_RETAILLINEITEM[] RETAILLINEITEM {
        get {
            return this.rETAILLINEITEMField;
        }
        set {
            this.rETAILLINEITEMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DISCOUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_RTI001_POSDW_DISCOUNT[] DISCOUNT {
        get {
            return this.dISCOUNTField;
        }
        set {
            this.dISCOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TENDER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_RTI001_POSDW_TENDER[] TENDER {
        get {
            return this.tENDERField;
        }
        set {
            this.tENDERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FINANCIALMOVEMENT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_RTI001_POSDW_FINANCIALMOVEMENT[] FINANCIALMOVEMENT {
        get {
            return this.fINANCIALMOVEMENTField;
        }
        set {
            this.fINANCIALMOVEMENTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ADVPAYMENT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public string[] ADVPAYMENTS {
        get {
            return this.aDVPAYMENTSField;
        }
        set {
            this.aDVPAYMENTSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://dohome.co.th/POSOutbound/RT")]
public partial class DT_RTI001_POSDW_RETAILLINEITEM {
    
    private string rETAILSEQUENCENUMBERField;
    
    private string rETAILTYPECODEField;
    
    private string rETAILREASONCODEField;
    
    private string iTEMIDQUALIFIERField;
    
    private string iTEMIDField;
    
    private string rETAILQUANTITYField;
    
    private string sALESUNITOFMEASUREField;
    
    private string sALESAMOUNTField;
    
    private string nORMALSALESAMOUNTField;
    
    private string cOSTField;
    
    private string pROMOTIONIDField;
    
    private string iTEMIDENTRYMETHODCODEField;
    
    private string aCTUALUNITPRICEField;
    
    private string uNITSField;
    
    private string sCANTIMEField;
    
    private DT_RTI001_POSDW_DISCOUNT[] dISCOUNTField;
    
    private DT_RTI001_POSDW_TAX[] tAXField;
    
    private DT_RTI001_POSDW_EXTENSIONS[] eXTENSIONSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RETAILSEQUENCENUMBER {
        get {
            return this.rETAILSEQUENCENUMBERField;
        }
        set {
            this.rETAILSEQUENCENUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RETAILTYPECODE {
        get {
            return this.rETAILTYPECODEField;
        }
        set {
            this.rETAILTYPECODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RETAILREASONCODE {
        get {
            return this.rETAILREASONCODEField;
        }
        set {
            this.rETAILREASONCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ITEMIDQUALIFIER {
        get {
            return this.iTEMIDQUALIFIERField;
        }
        set {
            this.iTEMIDQUALIFIERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ITEMID {
        get {
            return this.iTEMIDField;
        }
        set {
            this.iTEMIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RETAILQUANTITY {
        get {
            return this.rETAILQUANTITYField;
        }
        set {
            this.rETAILQUANTITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SALESUNITOFMEASURE {
        get {
            return this.sALESUNITOFMEASUREField;
        }
        set {
            this.sALESUNITOFMEASUREField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SALESAMOUNT {
        get {
            return this.sALESAMOUNTField;
        }
        set {
            this.sALESAMOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NORMALSALESAMOUNT {
        get {
            return this.nORMALSALESAMOUNTField;
        }
        set {
            this.nORMALSALESAMOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COST {
        get {
            return this.cOSTField;
        }
        set {
            this.cOSTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PROMOTIONID {
        get {
            return this.pROMOTIONIDField;
        }
        set {
            this.pROMOTIONIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ITEMIDENTRYMETHODCODE {
        get {
            return this.iTEMIDENTRYMETHODCODEField;
        }
        set {
            this.iTEMIDENTRYMETHODCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ACTUALUNITPRICE {
        get {
            return this.aCTUALUNITPRICEField;
        }
        set {
            this.aCTUALUNITPRICEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UNITS {
        get {
            return this.uNITSField;
        }
        set {
            this.uNITSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SCANTIME {
        get {
            return this.sCANTIMEField;
        }
        set {
            this.sCANTIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DISCOUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_RTI001_POSDW_DISCOUNT[] DISCOUNT {
        get {
            return this.dISCOUNTField;
        }
        set {
            this.dISCOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TAX", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_RTI001_POSDW_TAX[] TAX {
        get {
            return this.tAXField;
        }
        set {
            this.tAXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EXTENSIONS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_RTI001_POSDW_EXTENSIONS[] EXTENSIONS {
        get {
            return this.eXTENSIONSField;
        }
        set {
            this.eXTENSIONSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://dohome.co.th/POSOutbound/RT")]
public partial class DT_RTI001_POSDW_DISCOUNT {
    
    private string dISCOUNTSEQUENCENUMBERField;
    
    private string dISCOUNTTYPECODEField;
    
    private string dISCOUNTREASONCODEField;
    
    private string rEDUCTIONAMOUNTField;
    
    private string dISCOUNTIDField;
    
    private string bONUSBUYIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DISCOUNTSEQUENCENUMBER {
        get {
            return this.dISCOUNTSEQUENCENUMBERField;
        }
        set {
            this.dISCOUNTSEQUENCENUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DISCOUNTTYPECODE {
        get {
            return this.dISCOUNTTYPECODEField;
        }
        set {
            this.dISCOUNTTYPECODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DISCOUNTREASONCODE {
        get {
            return this.dISCOUNTREASONCODEField;
        }
        set {
            this.dISCOUNTREASONCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string REDUCTIONAMOUNT {
        get {
            return this.rEDUCTIONAMOUNTField;
        }
        set {
            this.rEDUCTIONAMOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DISCOUNTID {
        get {
            return this.dISCOUNTIDField;
        }
        set {
            this.dISCOUNTIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BONUSBUYID {
        get {
            return this.bONUSBUYIDField;
        }
        set {
            this.bONUSBUYIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://dohome.co.th/POSOutbound/RT")]
public partial class DT_RTI001_POSDW_FINANCIALMOVEMENT_EXTENSIONS {
    
    private string sONUMBERField;
    
    private string dUE_DATEField;
    
    private string cHEQUE_NOField;
    
    private string bANK_ACCOUNT_NOField;
    
    private string bANK_KEYField;
    
    private string dRAWER_NAMEField;
    
    private string dRAWER_CITYField;
    
    private string dRAWEE_NAMEField;
    
    private string dRAWEE_CITYField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SONUMBER {
        get {
            return this.sONUMBERField;
        }
        set {
            this.sONUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DUE_DATE {
        get {
            return this.dUE_DATEField;
        }
        set {
            this.dUE_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CHEQUE_NO {
        get {
            return this.cHEQUE_NOField;
        }
        set {
            this.cHEQUE_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BANK_ACCOUNT_NO {
        get {
            return this.bANK_ACCOUNT_NOField;
        }
        set {
            this.bANK_ACCOUNT_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BANK_KEY {
        get {
            return this.bANK_KEYField;
        }
        set {
            this.bANK_KEYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DRAWER_NAME {
        get {
            return this.dRAWER_NAMEField;
        }
        set {
            this.dRAWER_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DRAWER_CITY {
        get {
            return this.dRAWER_CITYField;
        }
        set {
            this.dRAWER_CITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DRAWEE_NAME {
        get {
            return this.dRAWEE_NAMEField;
        }
        set {
            this.dRAWEE_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DRAWEE_CITY {
        get {
            return this.dRAWEE_CITYField;
        }
        set {
            this.dRAWEE_CITYField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://dohome.co.th/POSOutbound/RT")]
public partial class DT_RTI001_POSDW_FINANCIALMOVEMENT {
    
    private string fINUMBERField;
    
    private string fITYPECODEField;
    
    private string aCCOUNTIDField;
    
    private string aCCOUNTASSIGNOBJField;
    
    private string aMOUNTField;
    
    private string fICURRENCYField;
    
    private string rEFERERENCEIDField;
    
    private DT_RTI001_POSDW_FINANCIALMOVEMENT_EXTENSIONS eXTENSIONSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FINUMBER {
        get {
            return this.fINUMBERField;
        }
        set {
            this.fINUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FITYPECODE {
        get {
            return this.fITYPECODEField;
        }
        set {
            this.fITYPECODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ACCOUNTID {
        get {
            return this.aCCOUNTIDField;
        }
        set {
            this.aCCOUNTIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ACCOUNTASSIGNOBJ {
        get {
            return this.aCCOUNTASSIGNOBJField;
        }
        set {
            this.aCCOUNTASSIGNOBJField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AMOUNT {
        get {
            return this.aMOUNTField;
        }
        set {
            this.aMOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FICURRENCY {
        get {
            return this.fICURRENCYField;
        }
        set {
            this.fICURRENCYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string REFERERENCEID {
        get {
            return this.rEFERERENCEIDField;
        }
        set {
            this.rEFERERENCEIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_RTI001_POSDW_FINANCIALMOVEMENT_EXTENSIONS EXTENSIONS {
        get {
            return this.eXTENSIONSField;
        }
        set {
            this.eXTENSIONSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://dohome.co.th/POSOutbound/RT")]
public partial class DT_RTI001_POSDW_TENDER {
    
    private string tENDERSEQUENCENUMBERField;
    
    private string tENDERTYPECODEField;
    
    private string tENDERAMOUNTField;
    
    private string tENDERCURRENCYField;
    
    private string tENDERIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TENDERSEQUENCENUMBER {
        get {
            return this.tENDERSEQUENCENUMBERField;
        }
        set {
            this.tENDERSEQUENCENUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TENDERTYPECODE {
        get {
            return this.tENDERTYPECODEField;
        }
        set {
            this.tENDERTYPECODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TENDERAMOUNT {
        get {
            return this.tENDERAMOUNTField;
        }
        set {
            this.tENDERAMOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TENDERCURRENCY {
        get {
            return this.tENDERCURRENCYField;
        }
        set {
            this.tENDERCURRENCYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TENDERID {
        get {
            return this.tENDERIDField;
        }
        set {
            this.tENDERIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://dohome.co.th/POSOutbound/RT")]
public partial class DT_RTI001_POSDW_EXTENSIONS {
    
    private string sONUMBERField;
    
    private string sOLINEITEMField;
    
    private string sLOCField;
    
    private string bATCHIDField;
    
    private string sERIALNUMBERField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SONUMBER {
        get {
            return this.sONUMBERField;
        }
        set {
            this.sONUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SOLINEITEM {
        get {
            return this.sOLINEITEMField;
        }
        set {
            this.sOLINEITEMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SLOC {
        get {
            return this.sLOCField;
        }
        set {
            this.sLOCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BATCHID {
        get {
            return this.bATCHIDField;
        }
        set {
            this.bATCHIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SERIALNUMBER {
        get {
            return this.sERIALNUMBERField;
        }
        set {
            this.sERIALNUMBERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://dohome.co.th/POSOutbound/RT")]
public partial class DT_RTI001_POSDW_TAX {
    
    private string tAXSEQUENCENUMBERField;
    
    private string tAXTYPECODEField;
    
    private string tAXAMOUNTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TAXSEQUENCENUMBER {
        get {
            return this.tAXSEQUENCENUMBERField;
        }
        set {
            this.tAXSEQUENCENUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TAXTYPECODE {
        get {
            return this.tAXTYPECODEField;
        }
        set {
            this.tAXTYPECODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TAXAMOUNT {
        get {
            return this.tAXAMOUNTField;
        }
        set {
            this.tAXAMOUNTField = value;
        }
    }
}
