#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Create_XML
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBTRANS")]
	public partial class POS_HDDTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBTrans_POS_HD(TBTrans_POS_HD instance);
    partial void UpdateTBTrans_POS_HD(TBTrans_POS_HD instance);
    partial void DeleteTBTrans_POS_HD(TBTrans_POS_HD instance);
    partial void InsertTBTrans_POS_DT(TBTrans_POS_DT instance);
    partial void UpdateTBTrans_POS_DT(TBTrans_POS_DT instance);
    partial void DeleteTBTrans_POS_DT(TBTrans_POS_DT instance);
    #endregion
		
		public POS_HDDTDataContext() : 
				base(global::Create_XML.Properties.Settings.Default.DBTRANSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public POS_HDDTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POS_HDDTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POS_HDDTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POS_HDDTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBTrans_POS_HD> TBTrans_POS_HDs
		{
			get
			{
				return this.GetTable<TBTrans_POS_HD>();
			}
		}
		
		public System.Data.Linq.Table<TBTrans_POS_DT> TBTrans_POS_DTs
		{
			get
			{
				return this.GetTable<TBTrans_POS_DT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBTrans_POS_HD")]
	public partial class TBTrans_POS_HD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BRANCHCODE;
		
		private string _SITECODE;
		
		private string _SALEORG;
		
		private string _DISCHAN;
		
		private string _DIVISION;
		
		private string _SALEOFF;
		
		private string _PLANT;
		
		private string _DOCNO;
		
		private System.DateTime _DOCDATE;
		
		private System.DateTime _CREATEDATE;
		
		private short _DOCTYPE;
		
		private string _ARCODE;
		
		private string _ARNAME;
		
		private string _PAYMENTCODE;
		
		private string _CASHIER;
		
		private string _ASSTCASHIER;
		
		private string _SALECODE;
		
		private short _TAXTYPE;
		
		private decimal _TAXRATE;
		
		private decimal _SUMDETAILAMOUNT;
		
		private decimal _SUMNOTAXAMOUNT;
		
		private decimal _SUMTAXAMOUNT;
		
		private decimal _TAXAMOUNT;
		
		private decimal _BEFOREROUNDDEBTAMOUNT;
		
		private decimal _DEBTAMOUNT;
		
		private decimal _DIFFROUNDDEBTAMOUNT;
		
		private decimal _SUMCOUPONAMOUNT;
		
		private decimal _SUMEDUCOUPONAMOUNT;
		
		private decimal _SUMBANKTRANSFER;
		
		private decimal _SUMCREDITAMOUNT;
		
		private decimal _SUMCHARGEAMOUNT;
		
		private decimal _SUMCHEQUEAMOUNT;
		
		private decimal _SUMPROMOTIONAMOUNT;
		
		private decimal _SUMVATCREDITCARDCHARGEAMOUNT;
		
		private decimal _SUMBONUSBUY_DISCOUNT;
		
		private decimal _SUMEMPLOYEE_DISCOUNT;
		
		private System.Nullable<decimal> _SUMFIDOCUMENT_AMOUNT;
		
		private decimal _TAXCHARGEAMOUNT;
		
		private decimal _CASHAMOUNT;
		
		private decimal _CHANGEAMOUNT;
		
		private short _SYSDOCFLAG;
		
		private string _SYSDOCREMARK;
		
		private short _CRFLAG;
		
		private string _CRREMARK;
		
		private decimal _CRTOTALAMOUNT;
		
		private decimal _CROVERAMOUNT;
		
		private short _CRAPPROVEFLAG;
		
		private string _CRAPPROVEUSERCODE;
		
		private string _CRAPPROVEUSERNAME;
		
		private System.Nullable<System.DateTime> _CRAPPROVETIME;
		
		private string _CRAPPROVEREASON;
		
		private string _REMARK;
		
		private string _DOCREFOUT;
		
		private string _HOLD_BILL_REMARK;
		
		private string _TAXNO;
		
		private System.Nullable<System.DateTime> _TAXDATE;
		
		private string _COMPUTERNAME;
		
		private string _POSCODE;
		
		private string _PRODUCTPROMOTION;
		
		private decimal _CALCCHARGEAMOUNT;
		
		private decimal _REMAINCALCCHARGEAMOUNT;
		
		private short _EXPORTFLAG;
		
		private string _SAPDOCNO;
		
		private string _ARCODETAX;
		
		private string _ARNAMETAX;
		
		private string _ARNAMEWT;
		
		private string _ARADDRWT;
		
		private short _WTSTATUS;
		
		private decimal _WTAMOUNT;
		
		private decimal _MANAGEPRICE;
		
		private decimal _RETURNAMOUNT;
		
		private short _PAYWTSTATUS;
		
		private short _ISUSEPROMOTIONPRICE;
		
		private string _CITY_WT;
		
		private string _PROVINCE_WT;
		
		private string _ZIPCODE_WT;
		
		private string _ARNAMERECMONEY;
		
		private string _IDCARDRECMONEY;
		
		private string _WTRETURNRATECODE;
		
		private decimal _WTRETURNRATE_CUS;
		
		private decimal _WTRETURNRATE_UW;
		
		private decimal _WTRETURNAMT_CUS;
		
		private decimal _WTRETURNAMT_UW;
		
		private string _CAR_LICENSE;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
		private System.Nullable<System.DateTime> _EXPORTFLAG_DATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBRANCHCODEChanging(string value);
    partial void OnBRANCHCODEChanged();
    partial void OnSITECODEChanging(string value);
    partial void OnSITECODEChanged();
    partial void OnSALEORGChanging(string value);
    partial void OnSALEORGChanged();
    partial void OnDISCHANChanging(string value);
    partial void OnDISCHANChanged();
    partial void OnDIVISIONChanging(string value);
    partial void OnDIVISIONChanged();
    partial void OnSALEOFFChanging(string value);
    partial void OnSALEOFFChanged();
    partial void OnPLANTChanging(string value);
    partial void OnPLANTChanged();
    partial void OnDOCNOChanging(string value);
    partial void OnDOCNOChanged();
    partial void OnDOCDATEChanging(System.DateTime value);
    partial void OnDOCDATEChanged();
    partial void OnCREATEDATEChanging(System.DateTime value);
    partial void OnCREATEDATEChanged();
    partial void OnDOCTYPEChanging(short value);
    partial void OnDOCTYPEChanged();
    partial void OnARCODEChanging(string value);
    partial void OnARCODEChanged();
    partial void OnARNAMEChanging(string value);
    partial void OnARNAMEChanged();
    partial void OnPAYMENTCODEChanging(string value);
    partial void OnPAYMENTCODEChanged();
    partial void OnCASHIERChanging(string value);
    partial void OnCASHIERChanged();
    partial void OnASSTCASHIERChanging(string value);
    partial void OnASSTCASHIERChanged();
    partial void OnSALECODEChanging(string value);
    partial void OnSALECODEChanged();
    partial void OnTAXTYPEChanging(short value);
    partial void OnTAXTYPEChanged();
    partial void OnTAXRATEChanging(decimal value);
    partial void OnTAXRATEChanged();
    partial void OnSUMDETAILAMOUNTChanging(decimal value);
    partial void OnSUMDETAILAMOUNTChanged();
    partial void OnSUMNOTAXAMOUNTChanging(decimal value);
    partial void OnSUMNOTAXAMOUNTChanged();
    partial void OnSUMTAXAMOUNTChanging(decimal value);
    partial void OnSUMTAXAMOUNTChanged();
    partial void OnTAXAMOUNTChanging(decimal value);
    partial void OnTAXAMOUNTChanged();
    partial void OnBEFOREROUNDDEBTAMOUNTChanging(decimal value);
    partial void OnBEFOREROUNDDEBTAMOUNTChanged();
    partial void OnDEBTAMOUNTChanging(decimal value);
    partial void OnDEBTAMOUNTChanged();
    partial void OnDIFFROUNDDEBTAMOUNTChanging(decimal value);
    partial void OnDIFFROUNDDEBTAMOUNTChanged();
    partial void OnSUMCOUPONAMOUNTChanging(decimal value);
    partial void OnSUMCOUPONAMOUNTChanged();
    partial void OnSUMEDUCOUPONAMOUNTChanging(decimal value);
    partial void OnSUMEDUCOUPONAMOUNTChanged();
    partial void OnSUMBANKTRANSFERChanging(decimal value);
    partial void OnSUMBANKTRANSFERChanged();
    partial void OnSUMCREDITAMOUNTChanging(decimal value);
    partial void OnSUMCREDITAMOUNTChanged();
    partial void OnSUMCHARGEAMOUNTChanging(decimal value);
    partial void OnSUMCHARGEAMOUNTChanged();
    partial void OnSUMCHEQUEAMOUNTChanging(decimal value);
    partial void OnSUMCHEQUEAMOUNTChanged();
    partial void OnSUMPROMOTIONAMOUNTChanging(decimal value);
    partial void OnSUMPROMOTIONAMOUNTChanged();
    partial void OnSUMVATCREDITCARDCHARGEAMOUNTChanging(decimal value);
    partial void OnSUMVATCREDITCARDCHARGEAMOUNTChanged();
    partial void OnSUMBONUSBUY_DISCOUNTChanging(decimal value);
    partial void OnSUMBONUSBUY_DISCOUNTChanged();
    partial void OnSUMEMPLOYEE_DISCOUNTChanging(decimal value);
    partial void OnSUMEMPLOYEE_DISCOUNTChanged();
    partial void OnSUMFIDOCUMENT_AMOUNTChanging(System.Nullable<decimal> value);
    partial void OnSUMFIDOCUMENT_AMOUNTChanged();
    partial void OnTAXCHARGEAMOUNTChanging(decimal value);
    partial void OnTAXCHARGEAMOUNTChanged();
    partial void OnCASHAMOUNTChanging(decimal value);
    partial void OnCASHAMOUNTChanged();
    partial void OnCHANGEAMOUNTChanging(decimal value);
    partial void OnCHANGEAMOUNTChanged();
    partial void OnSYSDOCFLAGChanging(short value);
    partial void OnSYSDOCFLAGChanged();
    partial void OnSYSDOCREMARKChanging(string value);
    partial void OnSYSDOCREMARKChanged();
    partial void OnCRFLAGChanging(short value);
    partial void OnCRFLAGChanged();
    partial void OnCRREMARKChanging(string value);
    partial void OnCRREMARKChanged();
    partial void OnCRTOTALAMOUNTChanging(decimal value);
    partial void OnCRTOTALAMOUNTChanged();
    partial void OnCROVERAMOUNTChanging(decimal value);
    partial void OnCROVERAMOUNTChanged();
    partial void OnCRAPPROVEFLAGChanging(short value);
    partial void OnCRAPPROVEFLAGChanged();
    partial void OnCRAPPROVEUSERCODEChanging(string value);
    partial void OnCRAPPROVEUSERCODEChanged();
    partial void OnCRAPPROVEUSERNAMEChanging(string value);
    partial void OnCRAPPROVEUSERNAMEChanged();
    partial void OnCRAPPROVETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnCRAPPROVETIMEChanged();
    partial void OnCRAPPROVEREASONChanging(string value);
    partial void OnCRAPPROVEREASONChanged();
    partial void OnREMARKChanging(string value);
    partial void OnREMARKChanged();
    partial void OnDOCREFOUTChanging(string value);
    partial void OnDOCREFOUTChanged();
    partial void OnHOLD_BILL_REMARKChanging(string value);
    partial void OnHOLD_BILL_REMARKChanged();
    partial void OnTAXNOChanging(string value);
    partial void OnTAXNOChanged();
    partial void OnTAXDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnTAXDATEChanged();
    partial void OnCOMPUTERNAMEChanging(string value);
    partial void OnCOMPUTERNAMEChanged();
    partial void OnPOSCODEChanging(string value);
    partial void OnPOSCODEChanged();
    partial void OnPRODUCTPROMOTIONChanging(string value);
    partial void OnPRODUCTPROMOTIONChanged();
    partial void OnCALCCHARGEAMOUNTChanging(decimal value);
    partial void OnCALCCHARGEAMOUNTChanged();
    partial void OnREMAINCALCCHARGEAMOUNTChanging(decimal value);
    partial void OnREMAINCALCCHARGEAMOUNTChanged();
    partial void OnEXPORTFLAGChanging(short value);
    partial void OnEXPORTFLAGChanged();
    partial void OnSAPDOCNOChanging(string value);
    partial void OnSAPDOCNOChanged();
    partial void OnARCODETAXChanging(string value);
    partial void OnARCODETAXChanged();
    partial void OnARNAMETAXChanging(string value);
    partial void OnARNAMETAXChanged();
    partial void OnARNAMEWTChanging(string value);
    partial void OnARNAMEWTChanged();
    partial void OnARADDRWTChanging(string value);
    partial void OnARADDRWTChanged();
    partial void OnWTSTATUSChanging(short value);
    partial void OnWTSTATUSChanged();
    partial void OnWTAMOUNTChanging(decimal value);
    partial void OnWTAMOUNTChanged();
    partial void OnMANAGEPRICEChanging(decimal value);
    partial void OnMANAGEPRICEChanged();
    partial void OnRETURNAMOUNTChanging(decimal value);
    partial void OnRETURNAMOUNTChanged();
    partial void OnPAYWTSTATUSChanging(short value);
    partial void OnPAYWTSTATUSChanged();
    partial void OnISUSEPROMOTIONPRICEChanging(short value);
    partial void OnISUSEPROMOTIONPRICEChanged();
    partial void OnCITY_WTChanging(string value);
    partial void OnCITY_WTChanged();
    partial void OnPROVINCE_WTChanging(string value);
    partial void OnPROVINCE_WTChanged();
    partial void OnZIPCODE_WTChanging(string value);
    partial void OnZIPCODE_WTChanged();
    partial void OnARNAMERECMONEYChanging(string value);
    partial void OnARNAMERECMONEYChanged();
    partial void OnIDCARDRECMONEYChanging(string value);
    partial void OnIDCARDRECMONEYChanged();
    partial void OnWTRETURNRATECODEChanging(string value);
    partial void OnWTRETURNRATECODEChanged();
    partial void OnWTRETURNRATE_CUSChanging(decimal value);
    partial void OnWTRETURNRATE_CUSChanged();
    partial void OnWTRETURNRATE_UWChanging(decimal value);
    partial void OnWTRETURNRATE_UWChanged();
    partial void OnWTRETURNAMT_CUSChanging(decimal value);
    partial void OnWTRETURNAMT_CUSChanged();
    partial void OnWTRETURNAMT_UWChanging(decimal value);
    partial void OnWTRETURNAMT_UWChanged();
    partial void OnCAR_LICENSEChanging(string value);
    partial void OnCAR_LICENSEChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    partial void OnEXPORTFLAG_DATE_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnEXPORTFLAG_DATE_TIMEChanged();
    #endregion
		
		public TBTrans_POS_HD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHCODE", DbType="VarChar(50)")]
		public string BRANCHCODE
		{
			get
			{
				return this._BRANCHCODE;
			}
			set
			{
				if ((this._BRANCHCODE != value))
				{
					this.OnBRANCHCODEChanging(value);
					this.SendPropertyChanging();
					this._BRANCHCODE = value;
					this.SendPropertyChanged("BRANCHCODE");
					this.OnBRANCHCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITECODE", DbType="VarChar(120)")]
		public string SITECODE
		{
			get
			{
				return this._SITECODE;
			}
			set
			{
				if ((this._SITECODE != value))
				{
					this.OnSITECODEChanging(value);
					this.SendPropertyChanging();
					this._SITECODE = value;
					this.SendPropertyChanged("SITECODE");
					this.OnSITECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALEORG", DbType="VarChar(120)")]
		public string SALEORG
		{
			get
			{
				return this._SALEORG;
			}
			set
			{
				if ((this._SALEORG != value))
				{
					this.OnSALEORGChanging(value);
					this.SendPropertyChanging();
					this._SALEORG = value;
					this.SendPropertyChanged("SALEORG");
					this.OnSALEORGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCHAN", DbType="VarChar(120)")]
		public string DISCHAN
		{
			get
			{
				return this._DISCHAN;
			}
			set
			{
				if ((this._DISCHAN != value))
				{
					this.OnDISCHANChanging(value);
					this.SendPropertyChanging();
					this._DISCHAN = value;
					this.SendPropertyChanged("DISCHAN");
					this.OnDISCHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISION", DbType="VarChar(120)")]
		public string DIVISION
		{
			get
			{
				return this._DIVISION;
			}
			set
			{
				if ((this._DIVISION != value))
				{
					this.OnDIVISIONChanging(value);
					this.SendPropertyChanging();
					this._DIVISION = value;
					this.SendPropertyChanged("DIVISION");
					this.OnDIVISIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALEOFF", DbType="VarChar(120)")]
		public string SALEOFF
		{
			get
			{
				return this._SALEOFF;
			}
			set
			{
				if ((this._SALEOFF != value))
				{
					this.OnSALEOFFChanging(value);
					this.SendPropertyChanging();
					this._SALEOFF = value;
					this.SendPropertyChanged("SALEOFF");
					this.OnSALEOFFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLANT", DbType="VarChar(120)")]
		public string PLANT
		{
			get
			{
				return this._PLANT;
			}
			set
			{
				if ((this._PLANT != value))
				{
					this.OnPLANTChanging(value);
					this.SendPropertyChanging();
					this._PLANT = value;
					this.SendPropertyChanged("PLANT");
					this.OnPLANTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNO", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOCNO
		{
			get
			{
				return this._DOCNO;
			}
			set
			{
				if ((this._DOCNO != value))
				{
					this.OnDOCNOChanging(value);
					this.SendPropertyChanging();
					this._DOCNO = value;
					this.SendPropertyChanged("DOCNO");
					this.OnDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime NOT NULL")]
		public System.DateTime DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime NOT NULL")]
		public System.DateTime CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCTYPE", DbType="SmallInt NOT NULL")]
		public short DOCTYPE
		{
			get
			{
				return this._DOCTYPE;
			}
			set
			{
				if ((this._DOCTYPE != value))
				{
					this.OnDOCTYPEChanging(value);
					this.SendPropertyChanging();
					this._DOCTYPE = value;
					this.SendPropertyChanged("DOCTYPE");
					this.OnDOCTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARCODE", DbType="VarChar(120)")]
		public string ARCODE
		{
			get
			{
				return this._ARCODE;
			}
			set
			{
				if ((this._ARCODE != value))
				{
					this.OnARCODEChanging(value);
					this.SendPropertyChanging();
					this._ARCODE = value;
					this.SendPropertyChanged("ARCODE");
					this.OnARCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARNAME", DbType="VarChar(250)")]
		public string ARNAME
		{
			get
			{
				return this._ARNAME;
			}
			set
			{
				if ((this._ARNAME != value))
				{
					this.OnARNAMEChanging(value);
					this.SendPropertyChanging();
					this._ARNAME = value;
					this.SendPropertyChanged("ARNAME");
					this.OnARNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYMENTCODE", DbType="VarChar(120)")]
		public string PAYMENTCODE
		{
			get
			{
				return this._PAYMENTCODE;
			}
			set
			{
				if ((this._PAYMENTCODE != value))
				{
					this.OnPAYMENTCODEChanging(value);
					this.SendPropertyChanging();
					this._PAYMENTCODE = value;
					this.SendPropertyChanged("PAYMENTCODE");
					this.OnPAYMENTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIER", DbType="VarChar(120)")]
		public string CASHIER
		{
			get
			{
				return this._CASHIER;
			}
			set
			{
				if ((this._CASHIER != value))
				{
					this.OnCASHIERChanging(value);
					this.SendPropertyChanging();
					this._CASHIER = value;
					this.SendPropertyChanged("CASHIER");
					this.OnCASHIERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSTCASHIER", DbType="VarChar(120)")]
		public string ASSTCASHIER
		{
			get
			{
				return this._ASSTCASHIER;
			}
			set
			{
				if ((this._ASSTCASHIER != value))
				{
					this.OnASSTCASHIERChanging(value);
					this.SendPropertyChanging();
					this._ASSTCASHIER = value;
					this.SendPropertyChanged("ASSTCASHIER");
					this.OnASSTCASHIERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALECODE", DbType="VarChar(120)")]
		public string SALECODE
		{
			get
			{
				return this._SALECODE;
			}
			set
			{
				if ((this._SALECODE != value))
				{
					this.OnSALECODEChanging(value);
					this.SendPropertyChanging();
					this._SALECODE = value;
					this.SendPropertyChanged("SALECODE");
					this.OnSALECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXTYPE", DbType="SmallInt NOT NULL")]
		public short TAXTYPE
		{
			get
			{
				return this._TAXTYPE;
			}
			set
			{
				if ((this._TAXTYPE != value))
				{
					this.OnTAXTYPEChanging(value);
					this.SendPropertyChanging();
					this._TAXTYPE = value;
					this.SendPropertyChanged("TAXTYPE");
					this.OnTAXTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXRATE", DbType="Money NOT NULL")]
		public decimal TAXRATE
		{
			get
			{
				return this._TAXRATE;
			}
			set
			{
				if ((this._TAXRATE != value))
				{
					this.OnTAXRATEChanging(value);
					this.SendPropertyChanging();
					this._TAXRATE = value;
					this.SendPropertyChanged("TAXRATE");
					this.OnTAXRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMDETAILAMOUNT", DbType="Money NOT NULL")]
		public decimal SUMDETAILAMOUNT
		{
			get
			{
				return this._SUMDETAILAMOUNT;
			}
			set
			{
				if ((this._SUMDETAILAMOUNT != value))
				{
					this.OnSUMDETAILAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMDETAILAMOUNT = value;
					this.SendPropertyChanged("SUMDETAILAMOUNT");
					this.OnSUMDETAILAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMNOTAXAMOUNT", DbType="Money NOT NULL")]
		public decimal SUMNOTAXAMOUNT
		{
			get
			{
				return this._SUMNOTAXAMOUNT;
			}
			set
			{
				if ((this._SUMNOTAXAMOUNT != value))
				{
					this.OnSUMNOTAXAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMNOTAXAMOUNT = value;
					this.SendPropertyChanged("SUMNOTAXAMOUNT");
					this.OnSUMNOTAXAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMTAXAMOUNT", DbType="Money NOT NULL")]
		public decimal SUMTAXAMOUNT
		{
			get
			{
				return this._SUMTAXAMOUNT;
			}
			set
			{
				if ((this._SUMTAXAMOUNT != value))
				{
					this.OnSUMTAXAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMTAXAMOUNT = value;
					this.SendPropertyChanged("SUMTAXAMOUNT");
					this.OnSUMTAXAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXAMOUNT", DbType="Money NOT NULL")]
		public decimal TAXAMOUNT
		{
			get
			{
				return this._TAXAMOUNT;
			}
			set
			{
				if ((this._TAXAMOUNT != value))
				{
					this.OnTAXAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._TAXAMOUNT = value;
					this.SendPropertyChanged("TAXAMOUNT");
					this.OnTAXAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEFOREROUNDDEBTAMOUNT", DbType="Money NOT NULL")]
		public decimal BEFOREROUNDDEBTAMOUNT
		{
			get
			{
				return this._BEFOREROUNDDEBTAMOUNT;
			}
			set
			{
				if ((this._BEFOREROUNDDEBTAMOUNT != value))
				{
					this.OnBEFOREROUNDDEBTAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._BEFOREROUNDDEBTAMOUNT = value;
					this.SendPropertyChanged("BEFOREROUNDDEBTAMOUNT");
					this.OnBEFOREROUNDDEBTAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEBTAMOUNT", DbType="Money NOT NULL")]
		public decimal DEBTAMOUNT
		{
			get
			{
				return this._DEBTAMOUNT;
			}
			set
			{
				if ((this._DEBTAMOUNT != value))
				{
					this.OnDEBTAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._DEBTAMOUNT = value;
					this.SendPropertyChanged("DEBTAMOUNT");
					this.OnDEBTAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIFFROUNDDEBTAMOUNT", DbType="Money NOT NULL")]
		public decimal DIFFROUNDDEBTAMOUNT
		{
			get
			{
				return this._DIFFROUNDDEBTAMOUNT;
			}
			set
			{
				if ((this._DIFFROUNDDEBTAMOUNT != value))
				{
					this.OnDIFFROUNDDEBTAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._DIFFROUNDDEBTAMOUNT = value;
					this.SendPropertyChanged("DIFFROUNDDEBTAMOUNT");
					this.OnDIFFROUNDDEBTAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMCOUPONAMOUNT", DbType="Money NOT NULL")]
		public decimal SUMCOUPONAMOUNT
		{
			get
			{
				return this._SUMCOUPONAMOUNT;
			}
			set
			{
				if ((this._SUMCOUPONAMOUNT != value))
				{
					this.OnSUMCOUPONAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMCOUPONAMOUNT = value;
					this.SendPropertyChanged("SUMCOUPONAMOUNT");
					this.OnSUMCOUPONAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMEDUCOUPONAMOUNT", DbType="Money NOT NULL")]
		public decimal SUMEDUCOUPONAMOUNT
		{
			get
			{
				return this._SUMEDUCOUPONAMOUNT;
			}
			set
			{
				if ((this._SUMEDUCOUPONAMOUNT != value))
				{
					this.OnSUMEDUCOUPONAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMEDUCOUPONAMOUNT = value;
					this.SendPropertyChanged("SUMEDUCOUPONAMOUNT");
					this.OnSUMEDUCOUPONAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMBANKTRANSFER", DbType="Money NOT NULL")]
		public decimal SUMBANKTRANSFER
		{
			get
			{
				return this._SUMBANKTRANSFER;
			}
			set
			{
				if ((this._SUMBANKTRANSFER != value))
				{
					this.OnSUMBANKTRANSFERChanging(value);
					this.SendPropertyChanging();
					this._SUMBANKTRANSFER = value;
					this.SendPropertyChanged("SUMBANKTRANSFER");
					this.OnSUMBANKTRANSFERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMCREDITAMOUNT", DbType="Money NOT NULL")]
		public decimal SUMCREDITAMOUNT
		{
			get
			{
				return this._SUMCREDITAMOUNT;
			}
			set
			{
				if ((this._SUMCREDITAMOUNT != value))
				{
					this.OnSUMCREDITAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMCREDITAMOUNT = value;
					this.SendPropertyChanged("SUMCREDITAMOUNT");
					this.OnSUMCREDITAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMCHARGEAMOUNT", DbType="Money NOT NULL")]
		public decimal SUMCHARGEAMOUNT
		{
			get
			{
				return this._SUMCHARGEAMOUNT;
			}
			set
			{
				if ((this._SUMCHARGEAMOUNT != value))
				{
					this.OnSUMCHARGEAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMCHARGEAMOUNT = value;
					this.SendPropertyChanged("SUMCHARGEAMOUNT");
					this.OnSUMCHARGEAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMCHEQUEAMOUNT", DbType="Money NOT NULL")]
		public decimal SUMCHEQUEAMOUNT
		{
			get
			{
				return this._SUMCHEQUEAMOUNT;
			}
			set
			{
				if ((this._SUMCHEQUEAMOUNT != value))
				{
					this.OnSUMCHEQUEAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMCHEQUEAMOUNT = value;
					this.SendPropertyChanged("SUMCHEQUEAMOUNT");
					this.OnSUMCHEQUEAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMPROMOTIONAMOUNT", DbType="Money NOT NULL")]
		public decimal SUMPROMOTIONAMOUNT
		{
			get
			{
				return this._SUMPROMOTIONAMOUNT;
			}
			set
			{
				if ((this._SUMPROMOTIONAMOUNT != value))
				{
					this.OnSUMPROMOTIONAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMPROMOTIONAMOUNT = value;
					this.SendPropertyChanged("SUMPROMOTIONAMOUNT");
					this.OnSUMPROMOTIONAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMVATCREDITCARDCHARGEAMOUNT", DbType="Money NOT NULL")]
		public decimal SUMVATCREDITCARDCHARGEAMOUNT
		{
			get
			{
				return this._SUMVATCREDITCARDCHARGEAMOUNT;
			}
			set
			{
				if ((this._SUMVATCREDITCARDCHARGEAMOUNT != value))
				{
					this.OnSUMVATCREDITCARDCHARGEAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMVATCREDITCARDCHARGEAMOUNT = value;
					this.SendPropertyChanged("SUMVATCREDITCARDCHARGEAMOUNT");
					this.OnSUMVATCREDITCARDCHARGEAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMBONUSBUY_DISCOUNT", DbType="Money NOT NULL")]
		public decimal SUMBONUSBUY_DISCOUNT
		{
			get
			{
				return this._SUMBONUSBUY_DISCOUNT;
			}
			set
			{
				if ((this._SUMBONUSBUY_DISCOUNT != value))
				{
					this.OnSUMBONUSBUY_DISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMBONUSBUY_DISCOUNT = value;
					this.SendPropertyChanged("SUMBONUSBUY_DISCOUNT");
					this.OnSUMBONUSBUY_DISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMEMPLOYEE_DISCOUNT", DbType="Money NOT NULL")]
		public decimal SUMEMPLOYEE_DISCOUNT
		{
			get
			{
				return this._SUMEMPLOYEE_DISCOUNT;
			}
			set
			{
				if ((this._SUMEMPLOYEE_DISCOUNT != value))
				{
					this.OnSUMEMPLOYEE_DISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMEMPLOYEE_DISCOUNT = value;
					this.SendPropertyChanged("SUMEMPLOYEE_DISCOUNT");
					this.OnSUMEMPLOYEE_DISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMFIDOCUMENT_AMOUNT", DbType="Money")]
		public System.Nullable<decimal> SUMFIDOCUMENT_AMOUNT
		{
			get
			{
				return this._SUMFIDOCUMENT_AMOUNT;
			}
			set
			{
				if ((this._SUMFIDOCUMENT_AMOUNT != value))
				{
					this.OnSUMFIDOCUMENT_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._SUMFIDOCUMENT_AMOUNT = value;
					this.SendPropertyChanged("SUMFIDOCUMENT_AMOUNT");
					this.OnSUMFIDOCUMENT_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXCHARGEAMOUNT", DbType="Money NOT NULL")]
		public decimal TAXCHARGEAMOUNT
		{
			get
			{
				return this._TAXCHARGEAMOUNT;
			}
			set
			{
				if ((this._TAXCHARGEAMOUNT != value))
				{
					this.OnTAXCHARGEAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._TAXCHARGEAMOUNT = value;
					this.SendPropertyChanged("TAXCHARGEAMOUNT");
					this.OnTAXCHARGEAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHAMOUNT", DbType="Money NOT NULL")]
		public decimal CASHAMOUNT
		{
			get
			{
				return this._CASHAMOUNT;
			}
			set
			{
				if ((this._CASHAMOUNT != value))
				{
					this.OnCASHAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._CASHAMOUNT = value;
					this.SendPropertyChanged("CASHAMOUNT");
					this.OnCASHAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGEAMOUNT", DbType="Money NOT NULL")]
		public decimal CHANGEAMOUNT
		{
			get
			{
				return this._CHANGEAMOUNT;
			}
			set
			{
				if ((this._CHANGEAMOUNT != value))
				{
					this.OnCHANGEAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._CHANGEAMOUNT = value;
					this.SendPropertyChanged("CHANGEAMOUNT");
					this.OnCHANGEAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSDOCFLAG", DbType="SmallInt NOT NULL")]
		public short SYSDOCFLAG
		{
			get
			{
				return this._SYSDOCFLAG;
			}
			set
			{
				if ((this._SYSDOCFLAG != value))
				{
					this.OnSYSDOCFLAGChanging(value);
					this.SendPropertyChanging();
					this._SYSDOCFLAG = value;
					this.SendPropertyChanged("SYSDOCFLAG");
					this.OnSYSDOCFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSDOCREMARK", DbType="VarChar(250)")]
		public string SYSDOCREMARK
		{
			get
			{
				return this._SYSDOCREMARK;
			}
			set
			{
				if ((this._SYSDOCREMARK != value))
				{
					this.OnSYSDOCREMARKChanging(value);
					this.SendPropertyChanging();
					this._SYSDOCREMARK = value;
					this.SendPropertyChanged("SYSDOCREMARK");
					this.OnSYSDOCREMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRFLAG", DbType="SmallInt NOT NULL")]
		public short CRFLAG
		{
			get
			{
				return this._CRFLAG;
			}
			set
			{
				if ((this._CRFLAG != value))
				{
					this.OnCRFLAGChanging(value);
					this.SendPropertyChanging();
					this._CRFLAG = value;
					this.SendPropertyChanged("CRFLAG");
					this.OnCRFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRREMARK", DbType="VarChar(250)")]
		public string CRREMARK
		{
			get
			{
				return this._CRREMARK;
			}
			set
			{
				if ((this._CRREMARK != value))
				{
					this.OnCRREMARKChanging(value);
					this.SendPropertyChanging();
					this._CRREMARK = value;
					this.SendPropertyChanged("CRREMARK");
					this.OnCRREMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTOTALAMOUNT", DbType="Money NOT NULL")]
		public decimal CRTOTALAMOUNT
		{
			get
			{
				return this._CRTOTALAMOUNT;
			}
			set
			{
				if ((this._CRTOTALAMOUNT != value))
				{
					this.OnCRTOTALAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._CRTOTALAMOUNT = value;
					this.SendPropertyChanged("CRTOTALAMOUNT");
					this.OnCRTOTALAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CROVERAMOUNT", DbType="Money NOT NULL")]
		public decimal CROVERAMOUNT
		{
			get
			{
				return this._CROVERAMOUNT;
			}
			set
			{
				if ((this._CROVERAMOUNT != value))
				{
					this.OnCROVERAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._CROVERAMOUNT = value;
					this.SendPropertyChanged("CROVERAMOUNT");
					this.OnCROVERAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRAPPROVEFLAG", DbType="SmallInt NOT NULL")]
		public short CRAPPROVEFLAG
		{
			get
			{
				return this._CRAPPROVEFLAG;
			}
			set
			{
				if ((this._CRAPPROVEFLAG != value))
				{
					this.OnCRAPPROVEFLAGChanging(value);
					this.SendPropertyChanging();
					this._CRAPPROVEFLAG = value;
					this.SendPropertyChanged("CRAPPROVEFLAG");
					this.OnCRAPPROVEFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRAPPROVEUSERCODE", DbType="VarChar(120)")]
		public string CRAPPROVEUSERCODE
		{
			get
			{
				return this._CRAPPROVEUSERCODE;
			}
			set
			{
				if ((this._CRAPPROVEUSERCODE != value))
				{
					this.OnCRAPPROVEUSERCODEChanging(value);
					this.SendPropertyChanging();
					this._CRAPPROVEUSERCODE = value;
					this.SendPropertyChanged("CRAPPROVEUSERCODE");
					this.OnCRAPPROVEUSERCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRAPPROVEUSERNAME", DbType="VarChar(250)")]
		public string CRAPPROVEUSERNAME
		{
			get
			{
				return this._CRAPPROVEUSERNAME;
			}
			set
			{
				if ((this._CRAPPROVEUSERNAME != value))
				{
					this.OnCRAPPROVEUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._CRAPPROVEUSERNAME = value;
					this.SendPropertyChanged("CRAPPROVEUSERNAME");
					this.OnCRAPPROVEUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRAPPROVETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> CRAPPROVETIME
		{
			get
			{
				return this._CRAPPROVETIME;
			}
			set
			{
				if ((this._CRAPPROVETIME != value))
				{
					this.OnCRAPPROVETIMEChanging(value);
					this.SendPropertyChanging();
					this._CRAPPROVETIME = value;
					this.SendPropertyChanged("CRAPPROVETIME");
					this.OnCRAPPROVETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRAPPROVEREASON", DbType="VarChar(250)")]
		public string CRAPPROVEREASON
		{
			get
			{
				return this._CRAPPROVEREASON;
			}
			set
			{
				if ((this._CRAPPROVEREASON != value))
				{
					this.OnCRAPPROVEREASONChanging(value);
					this.SendPropertyChanging();
					this._CRAPPROVEREASON = value;
					this.SendPropertyChanged("CRAPPROVEREASON");
					this.OnCRAPPROVEREASONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARK", DbType="VarChar(250)")]
		public string REMARK
		{
			get
			{
				return this._REMARK;
			}
			set
			{
				if ((this._REMARK != value))
				{
					this.OnREMARKChanging(value);
					this.SendPropertyChanging();
					this._REMARK = value;
					this.SendPropertyChanged("REMARK");
					this.OnREMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCREFOUT", DbType="VarChar(250)")]
		public string DOCREFOUT
		{
			get
			{
				return this._DOCREFOUT;
			}
			set
			{
				if ((this._DOCREFOUT != value))
				{
					this.OnDOCREFOUTChanging(value);
					this.SendPropertyChanging();
					this._DOCREFOUT = value;
					this.SendPropertyChanged("DOCREFOUT");
					this.OnDOCREFOUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOLD_BILL_REMARK", DbType="VarChar(200)")]
		public string HOLD_BILL_REMARK
		{
			get
			{
				return this._HOLD_BILL_REMARK;
			}
			set
			{
				if ((this._HOLD_BILL_REMARK != value))
				{
					this.OnHOLD_BILL_REMARKChanging(value);
					this.SendPropertyChanging();
					this._HOLD_BILL_REMARK = value;
					this.SendPropertyChanged("HOLD_BILL_REMARK");
					this.OnHOLD_BILL_REMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXNO", DbType="VarChar(120)")]
		public string TAXNO
		{
			get
			{
				return this._TAXNO;
			}
			set
			{
				if ((this._TAXNO != value))
				{
					this.OnTAXNOChanging(value);
					this.SendPropertyChanging();
					this._TAXNO = value;
					this.SendPropertyChanged("TAXNO");
					this.OnTAXNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> TAXDATE
		{
			get
			{
				return this._TAXDATE;
			}
			set
			{
				if ((this._TAXDATE != value))
				{
					this.OnTAXDATEChanging(value);
					this.SendPropertyChanging();
					this._TAXDATE = value;
					this.SendPropertyChanged("TAXDATE");
					this.OnTAXDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPUTERNAME", DbType="VarChar(150)")]
		public string COMPUTERNAME
		{
			get
			{
				return this._COMPUTERNAME;
			}
			set
			{
				if ((this._COMPUTERNAME != value))
				{
					this.OnCOMPUTERNAMEChanging(value);
					this.SendPropertyChanging();
					this._COMPUTERNAME = value;
					this.SendPropertyChanged("COMPUTERNAME");
					this.OnCOMPUTERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSCODE", DbType="VarChar(120)")]
		public string POSCODE
		{
			get
			{
				return this._POSCODE;
			}
			set
			{
				if ((this._POSCODE != value))
				{
					this.OnPOSCODEChanging(value);
					this.SendPropertyChanging();
					this._POSCODE = value;
					this.SendPropertyChanged("POSCODE");
					this.OnPOSCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTPROMOTION", DbType="VarChar(120)")]
		public string PRODUCTPROMOTION
		{
			get
			{
				return this._PRODUCTPROMOTION;
			}
			set
			{
				if ((this._PRODUCTPROMOTION != value))
				{
					this.OnPRODUCTPROMOTIONChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTPROMOTION = value;
					this.SendPropertyChanged("PRODUCTPROMOTION");
					this.OnPRODUCTPROMOTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALCCHARGEAMOUNT", DbType="Money NOT NULL")]
		public decimal CALCCHARGEAMOUNT
		{
			get
			{
				return this._CALCCHARGEAMOUNT;
			}
			set
			{
				if ((this._CALCCHARGEAMOUNT != value))
				{
					this.OnCALCCHARGEAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._CALCCHARGEAMOUNT = value;
					this.SendPropertyChanged("CALCCHARGEAMOUNT");
					this.OnCALCCHARGEAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMAINCALCCHARGEAMOUNT", DbType="Money NOT NULL")]
		public decimal REMAINCALCCHARGEAMOUNT
		{
			get
			{
				return this._REMAINCALCCHARGEAMOUNT;
			}
			set
			{
				if ((this._REMAINCALCCHARGEAMOUNT != value))
				{
					this.OnREMAINCALCCHARGEAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._REMAINCALCCHARGEAMOUNT = value;
					this.SendPropertyChanged("REMAINCALCCHARGEAMOUNT");
					this.OnREMAINCALCCHARGEAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXPORTFLAG", DbType="SmallInt NOT NULL")]
		public short EXPORTFLAG
		{
			get
			{
				return this._EXPORTFLAG;
			}
			set
			{
				if ((this._EXPORTFLAG != value))
				{
					this.OnEXPORTFLAGChanging(value);
					this.SendPropertyChanging();
					this._EXPORTFLAG = value;
					this.SendPropertyChanged("EXPORTFLAG");
					this.OnEXPORTFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPDOCNO", DbType="VarChar(120)")]
		public string SAPDOCNO
		{
			get
			{
				return this._SAPDOCNO;
			}
			set
			{
				if ((this._SAPDOCNO != value))
				{
					this.OnSAPDOCNOChanging(value);
					this.SendPropertyChanging();
					this._SAPDOCNO = value;
					this.SendPropertyChanged("SAPDOCNO");
					this.OnSAPDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARCODETAX", DbType="VarChar(120)")]
		public string ARCODETAX
		{
			get
			{
				return this._ARCODETAX;
			}
			set
			{
				if ((this._ARCODETAX != value))
				{
					this.OnARCODETAXChanging(value);
					this.SendPropertyChanging();
					this._ARCODETAX = value;
					this.SendPropertyChanged("ARCODETAX");
					this.OnARCODETAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARNAMETAX", DbType="VarChar(250)")]
		public string ARNAMETAX
		{
			get
			{
				return this._ARNAMETAX;
			}
			set
			{
				if ((this._ARNAMETAX != value))
				{
					this.OnARNAMETAXChanging(value);
					this.SendPropertyChanging();
					this._ARNAMETAX = value;
					this.SendPropertyChanged("ARNAMETAX");
					this.OnARNAMETAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARNAMEWT", DbType="VarChar(250)")]
		public string ARNAMEWT
		{
			get
			{
				return this._ARNAMEWT;
			}
			set
			{
				if ((this._ARNAMEWT != value))
				{
					this.OnARNAMEWTChanging(value);
					this.SendPropertyChanging();
					this._ARNAMEWT = value;
					this.SendPropertyChanged("ARNAMEWT");
					this.OnARNAMEWTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARADDRWT", DbType="VarChar(250)")]
		public string ARADDRWT
		{
			get
			{
				return this._ARADDRWT;
			}
			set
			{
				if ((this._ARADDRWT != value))
				{
					this.OnARADDRWTChanging(value);
					this.SendPropertyChanging();
					this._ARADDRWT = value;
					this.SendPropertyChanged("ARADDRWT");
					this.OnARADDRWTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WTSTATUS", DbType="SmallInt NOT NULL")]
		public short WTSTATUS
		{
			get
			{
				return this._WTSTATUS;
			}
			set
			{
				if ((this._WTSTATUS != value))
				{
					this.OnWTSTATUSChanging(value);
					this.SendPropertyChanging();
					this._WTSTATUS = value;
					this.SendPropertyChanged("WTSTATUS");
					this.OnWTSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WTAMOUNT", DbType="Money NOT NULL")]
		public decimal WTAMOUNT
		{
			get
			{
				return this._WTAMOUNT;
			}
			set
			{
				if ((this._WTAMOUNT != value))
				{
					this.OnWTAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._WTAMOUNT = value;
					this.SendPropertyChanged("WTAMOUNT");
					this.OnWTAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGEPRICE", DbType="Money NOT NULL")]
		public decimal MANAGEPRICE
		{
			get
			{
				return this._MANAGEPRICE;
			}
			set
			{
				if ((this._MANAGEPRICE != value))
				{
					this.OnMANAGEPRICEChanging(value);
					this.SendPropertyChanging();
					this._MANAGEPRICE = value;
					this.SendPropertyChanged("MANAGEPRICE");
					this.OnMANAGEPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RETURNAMOUNT", DbType="Money NOT NULL")]
		public decimal RETURNAMOUNT
		{
			get
			{
				return this._RETURNAMOUNT;
			}
			set
			{
				if ((this._RETURNAMOUNT != value))
				{
					this.OnRETURNAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._RETURNAMOUNT = value;
					this.SendPropertyChanged("RETURNAMOUNT");
					this.OnRETURNAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYWTSTATUS", DbType="SmallInt NOT NULL")]
		public short PAYWTSTATUS
		{
			get
			{
				return this._PAYWTSTATUS;
			}
			set
			{
				if ((this._PAYWTSTATUS != value))
				{
					this.OnPAYWTSTATUSChanging(value);
					this.SendPropertyChanging();
					this._PAYWTSTATUS = value;
					this.SendPropertyChanged("PAYWTSTATUS");
					this.OnPAYWTSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISUSEPROMOTIONPRICE", DbType="SmallInt NOT NULL")]
		public short ISUSEPROMOTIONPRICE
		{
			get
			{
				return this._ISUSEPROMOTIONPRICE;
			}
			set
			{
				if ((this._ISUSEPROMOTIONPRICE != value))
				{
					this.OnISUSEPROMOTIONPRICEChanging(value);
					this.SendPropertyChanging();
					this._ISUSEPROMOTIONPRICE = value;
					this.SendPropertyChanged("ISUSEPROMOTIONPRICE");
					this.OnISUSEPROMOTIONPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY_WT", DbType="VarChar(120)")]
		public string CITY_WT
		{
			get
			{
				return this._CITY_WT;
			}
			set
			{
				if ((this._CITY_WT != value))
				{
					this.OnCITY_WTChanging(value);
					this.SendPropertyChanging();
					this._CITY_WT = value;
					this.SendPropertyChanged("CITY_WT");
					this.OnCITY_WTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVINCE_WT", DbType="VarChar(120)")]
		public string PROVINCE_WT
		{
			get
			{
				return this._PROVINCE_WT;
			}
			set
			{
				if ((this._PROVINCE_WT != value))
				{
					this.OnPROVINCE_WTChanging(value);
					this.SendPropertyChanging();
					this._PROVINCE_WT = value;
					this.SendPropertyChanged("PROVINCE_WT");
					this.OnPROVINCE_WTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIPCODE_WT", DbType="VarChar(120)")]
		public string ZIPCODE_WT
		{
			get
			{
				return this._ZIPCODE_WT;
			}
			set
			{
				if ((this._ZIPCODE_WT != value))
				{
					this.OnZIPCODE_WTChanging(value);
					this.SendPropertyChanging();
					this._ZIPCODE_WT = value;
					this.SendPropertyChanged("ZIPCODE_WT");
					this.OnZIPCODE_WTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARNAMERECMONEY", DbType="VarChar(250)")]
		public string ARNAMERECMONEY
		{
			get
			{
				return this._ARNAMERECMONEY;
			}
			set
			{
				if ((this._ARNAMERECMONEY != value))
				{
					this.OnARNAMERECMONEYChanging(value);
					this.SendPropertyChanging();
					this._ARNAMERECMONEY = value;
					this.SendPropertyChanged("ARNAMERECMONEY");
					this.OnARNAMERECMONEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCARDRECMONEY", DbType="VarChar(120)")]
		public string IDCARDRECMONEY
		{
			get
			{
				return this._IDCARDRECMONEY;
			}
			set
			{
				if ((this._IDCARDRECMONEY != value))
				{
					this.OnIDCARDRECMONEYChanging(value);
					this.SendPropertyChanging();
					this._IDCARDRECMONEY = value;
					this.SendPropertyChanged("IDCARDRECMONEY");
					this.OnIDCARDRECMONEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WTRETURNRATECODE", DbType="VarChar(120)")]
		public string WTRETURNRATECODE
		{
			get
			{
				return this._WTRETURNRATECODE;
			}
			set
			{
				if ((this._WTRETURNRATECODE != value))
				{
					this.OnWTRETURNRATECODEChanging(value);
					this.SendPropertyChanging();
					this._WTRETURNRATECODE = value;
					this.SendPropertyChanged("WTRETURNRATECODE");
					this.OnWTRETURNRATECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WTRETURNRATE_CUS", DbType="Money NOT NULL")]
		public decimal WTRETURNRATE_CUS
		{
			get
			{
				return this._WTRETURNRATE_CUS;
			}
			set
			{
				if ((this._WTRETURNRATE_CUS != value))
				{
					this.OnWTRETURNRATE_CUSChanging(value);
					this.SendPropertyChanging();
					this._WTRETURNRATE_CUS = value;
					this.SendPropertyChanged("WTRETURNRATE_CUS");
					this.OnWTRETURNRATE_CUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WTRETURNRATE_UW", DbType="Money NOT NULL")]
		public decimal WTRETURNRATE_UW
		{
			get
			{
				return this._WTRETURNRATE_UW;
			}
			set
			{
				if ((this._WTRETURNRATE_UW != value))
				{
					this.OnWTRETURNRATE_UWChanging(value);
					this.SendPropertyChanging();
					this._WTRETURNRATE_UW = value;
					this.SendPropertyChanged("WTRETURNRATE_UW");
					this.OnWTRETURNRATE_UWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WTRETURNAMT_CUS", DbType="Money NOT NULL")]
		public decimal WTRETURNAMT_CUS
		{
			get
			{
				return this._WTRETURNAMT_CUS;
			}
			set
			{
				if ((this._WTRETURNAMT_CUS != value))
				{
					this.OnWTRETURNAMT_CUSChanging(value);
					this.SendPropertyChanging();
					this._WTRETURNAMT_CUS = value;
					this.SendPropertyChanged("WTRETURNAMT_CUS");
					this.OnWTRETURNAMT_CUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WTRETURNAMT_UW", DbType="Money NOT NULL")]
		public decimal WTRETURNAMT_UW
		{
			get
			{
				return this._WTRETURNAMT_UW;
			}
			set
			{
				if ((this._WTRETURNAMT_UW != value))
				{
					this.OnWTRETURNAMT_UWChanging(value);
					this.SendPropertyChanging();
					this._WTRETURNAMT_UW = value;
					this.SendPropertyChanged("WTRETURNAMT_UW");
					this.OnWTRETURNAMT_UWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAR_LICENSE", DbType="VarChar(100)")]
		public string CAR_LICENSE
		{
			get
			{
				return this._CAR_LICENSE;
			}
			set
			{
				if ((this._CAR_LICENSE != value))
				{
					this.OnCAR_LICENSEChanging(value);
					this.SendPropertyChanging();
					this._CAR_LICENSE = value;
					this.SendPropertyChanged("CAR_LICENSE");
					this.OnCAR_LICENSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXPORTFLAG_DATE_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> EXPORTFLAG_DATE_TIME
		{
			get
			{
				return this._EXPORTFLAG_DATE_TIME;
			}
			set
			{
				if ((this._EXPORTFLAG_DATE_TIME != value))
				{
					this.OnEXPORTFLAG_DATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._EXPORTFLAG_DATE_TIME = value;
					this.SendPropertyChanged("EXPORTFLAG_DATE_TIME");
					this.OnEXPORTFLAG_DATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBTrans_POS_DT")]
	public partial class TBTrans_POS_DT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DOCNO;
		
		private System.DateTime _DOCDATE;
		
		private string _ARCODE;
		
		private short _ROWORDER;
		
		private short _ITEMTAXTYPE;
		
		private string _PRODUCTCODE;
		
		private string _PRODUCTNAME;
		
		private string _BARCODE;
		
		private string _SITECODE;
		
		private string _SLOC;
		
		private string _LOCATION;
		
		private string _UNITCODE;
		
		private decimal _UNITRATE;
		
		private decimal _QUANTITY;
		
		private decimal _REMAINQTY;
		
		private decimal _STDUNITPRICE;
		
		private decimal _TAXVALUE;
		
		private decimal _UNITPRICEBEFORETAX;
		
		private decimal _UNITPRICE;
		
		private System.Nullable<decimal> _UNITPRICE_BEFORE_ADD;
		
		private decimal _NETAMOUNT;
		
		private string _SALECODE;
		
		private string _PCCODE;
		
		private string _REMARK;
		
		private short _CANCELFLAG;
		
		private string _CANCELREASON;
		
		private string _USERCODEAPPROVE;
		
		private short _EXPORTFLAG;
		
		private string _SAPDOCNO;
		
		private string _SAPREFDOCNO;
		
		private short _STOCKEXPORTFLAG;
		
		private string _SAPSTOCKDOCNO;
		
		private short _MATERIALTYPE;
		
		private short _SALEROWORDER;
		
		private short _CANCELROWORDER;
		
		private string _MTPOS;
		
		private decimal _UNITPRICECALVAT;
		
		private decimal _NETAMOUNTCALVAT;
		
		private short _CRCHARGEFLAG;
		
		private string _SALECOLORDOCNO;
		
		private string _SALECOLORFORMULANAME;
		
		private decimal _SALECOLORFORMULASALEQTY;
		
		private short _SALECOLORROWORDER;
		
		private System.Nullable<short> _SYSDOCFLAG;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private decimal _ZO02PERCENT;
		
		private decimal _ZO02VALUE;
		
		private decimal _UNITPRICEOLD;
		
		private short _ISPROMOTIONPRICE;
		
		private decimal _UNITPRICECALVATOLD;
		
		private decimal _UNITPRICECHARGE;
		
		private decimal _UNITPRICEWT;
		
		private decimal _UNITPRICEWT_CUS;
		
		private decimal _UNITPRICEWT_UW;
		
		private decimal _NETAMOUNTWT_CUS;
		
		private decimal _NETAMOUNTWT_UW;
		
		private string _PROMOTION_NUMBER;
		
		private string _BONUSBUY_ID;
		
		private string _PROMOTION_PRICE_NO;
		
		private System.Nullable<int> _PROMOTION_PRICE_ROWORDER;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
		private decimal _DISCOUNT;
		
		private System.Nullable<decimal> _TAX_AFTER_DISCOUNT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOCNOChanging(string value);
    partial void OnDOCNOChanged();
    partial void OnDOCDATEChanging(System.DateTime value);
    partial void OnDOCDATEChanged();
    partial void OnARCODEChanging(string value);
    partial void OnARCODEChanged();
    partial void OnROWORDERChanging(short value);
    partial void OnROWORDERChanged();
    partial void OnITEMTAXTYPEChanging(short value);
    partial void OnITEMTAXTYPEChanged();
    partial void OnPRODUCTCODEChanging(string value);
    partial void OnPRODUCTCODEChanged();
    partial void OnPRODUCTNAMEChanging(string value);
    partial void OnPRODUCTNAMEChanged();
    partial void OnBARCODEChanging(string value);
    partial void OnBARCODEChanged();
    partial void OnSITECODEChanging(string value);
    partial void OnSITECODEChanged();
    partial void OnSLOCChanging(string value);
    partial void OnSLOCChanged();
    partial void OnLOCATIONChanging(string value);
    partial void OnLOCATIONChanged();
    partial void OnUNITCODEChanging(string value);
    partial void OnUNITCODEChanged();
    partial void OnUNITRATEChanging(decimal value);
    partial void OnUNITRATEChanged();
    partial void OnQUANTITYChanging(decimal value);
    partial void OnQUANTITYChanged();
    partial void OnREMAINQTYChanging(decimal value);
    partial void OnREMAINQTYChanged();
    partial void OnSTDUNITPRICEChanging(decimal value);
    partial void OnSTDUNITPRICEChanged();
    partial void OnTAXVALUEChanging(decimal value);
    partial void OnTAXVALUEChanged();
    partial void OnUNITPRICEBEFORETAXChanging(decimal value);
    partial void OnUNITPRICEBEFORETAXChanged();
    partial void OnUNITPRICEChanging(decimal value);
    partial void OnUNITPRICEChanged();
    partial void OnUNITPRICE_BEFORE_ADDChanging(System.Nullable<decimal> value);
    partial void OnUNITPRICE_BEFORE_ADDChanged();
    partial void OnNETAMOUNTChanging(decimal value);
    partial void OnNETAMOUNTChanged();
    partial void OnSALECODEChanging(string value);
    partial void OnSALECODEChanged();
    partial void OnPCCODEChanging(string value);
    partial void OnPCCODEChanged();
    partial void OnREMARKChanging(string value);
    partial void OnREMARKChanged();
    partial void OnCANCELFLAGChanging(short value);
    partial void OnCANCELFLAGChanged();
    partial void OnCANCELREASONChanging(string value);
    partial void OnCANCELREASONChanged();
    partial void OnUSERCODEAPPROVEChanging(string value);
    partial void OnUSERCODEAPPROVEChanged();
    partial void OnEXPORTFLAGChanging(short value);
    partial void OnEXPORTFLAGChanged();
    partial void OnSAPDOCNOChanging(string value);
    partial void OnSAPDOCNOChanged();
    partial void OnSAPREFDOCNOChanging(string value);
    partial void OnSAPREFDOCNOChanged();
    partial void OnSTOCKEXPORTFLAGChanging(short value);
    partial void OnSTOCKEXPORTFLAGChanged();
    partial void OnSAPSTOCKDOCNOChanging(string value);
    partial void OnSAPSTOCKDOCNOChanged();
    partial void OnMATERIALTYPEChanging(short value);
    partial void OnMATERIALTYPEChanged();
    partial void OnSALEROWORDERChanging(short value);
    partial void OnSALEROWORDERChanged();
    partial void OnCANCELROWORDERChanging(short value);
    partial void OnCANCELROWORDERChanged();
    partial void OnMTPOSChanging(string value);
    partial void OnMTPOSChanged();
    partial void OnUNITPRICECALVATChanging(decimal value);
    partial void OnUNITPRICECALVATChanged();
    partial void OnNETAMOUNTCALVATChanging(decimal value);
    partial void OnNETAMOUNTCALVATChanged();
    partial void OnCRCHARGEFLAGChanging(short value);
    partial void OnCRCHARGEFLAGChanged();
    partial void OnSALECOLORDOCNOChanging(string value);
    partial void OnSALECOLORDOCNOChanged();
    partial void OnSALECOLORFORMULANAMEChanging(string value);
    partial void OnSALECOLORFORMULANAMEChanged();
    partial void OnSALECOLORFORMULASALEQTYChanging(decimal value);
    partial void OnSALECOLORFORMULASALEQTYChanged();
    partial void OnSALECOLORROWORDERChanging(short value);
    partial void OnSALECOLORROWORDERChanged();
    partial void OnSYSDOCFLAGChanging(System.Nullable<short> value);
    partial void OnSYSDOCFLAGChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    partial void OnZO02PERCENTChanging(decimal value);
    partial void OnZO02PERCENTChanged();
    partial void OnZO02VALUEChanging(decimal value);
    partial void OnZO02VALUEChanged();
    partial void OnUNITPRICEOLDChanging(decimal value);
    partial void OnUNITPRICEOLDChanged();
    partial void OnISPROMOTIONPRICEChanging(short value);
    partial void OnISPROMOTIONPRICEChanged();
    partial void OnUNITPRICECALVATOLDChanging(decimal value);
    partial void OnUNITPRICECALVATOLDChanged();
    partial void OnUNITPRICECHARGEChanging(decimal value);
    partial void OnUNITPRICECHARGEChanged();
    partial void OnUNITPRICEWTChanging(decimal value);
    partial void OnUNITPRICEWTChanged();
    partial void OnUNITPRICEWT_CUSChanging(decimal value);
    partial void OnUNITPRICEWT_CUSChanged();
    partial void OnUNITPRICEWT_UWChanging(decimal value);
    partial void OnUNITPRICEWT_UWChanged();
    partial void OnNETAMOUNTWT_CUSChanging(decimal value);
    partial void OnNETAMOUNTWT_CUSChanged();
    partial void OnNETAMOUNTWT_UWChanging(decimal value);
    partial void OnNETAMOUNTWT_UWChanged();
    partial void OnPROMOTION_NUMBERChanging(string value);
    partial void OnPROMOTION_NUMBERChanged();
    partial void OnBONUSBUY_IDChanging(string value);
    partial void OnBONUSBUY_IDChanged();
    partial void OnPROMOTION_PRICE_NOChanging(string value);
    partial void OnPROMOTION_PRICE_NOChanged();
    partial void OnPROMOTION_PRICE_ROWORDERChanging(System.Nullable<int> value);
    partial void OnPROMOTION_PRICE_ROWORDERChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    partial void OnDISCOUNTChanging(decimal value);
    partial void OnDISCOUNTChanged();
    partial void OnTAX_AFTER_DISCOUNTChanging(System.Nullable<decimal> value);
    partial void OnTAX_AFTER_DISCOUNTChanged();
    #endregion
		
		public TBTrans_POS_DT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNO", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOCNO
		{
			get
			{
				return this._DOCNO;
			}
			set
			{
				if ((this._DOCNO != value))
				{
					this.OnDOCNOChanging(value);
					this.SendPropertyChanging();
					this._DOCNO = value;
					this.SendPropertyChanged("DOCNO");
					this.OnDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime NOT NULL")]
		public System.DateTime DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARCODE", DbType="VarChar(20)")]
		public string ARCODE
		{
			get
			{
				return this._ARCODE;
			}
			set
			{
				if ((this._ARCODE != value))
				{
					this.OnARCODEChanging(value);
					this.SendPropertyChanging();
					this._ARCODE = value;
					this.SendPropertyChanged("ARCODE");
					this.OnARCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWORDER", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short ROWORDER
		{
			get
			{
				return this._ROWORDER;
			}
			set
			{
				if ((this._ROWORDER != value))
				{
					this.OnROWORDERChanging(value);
					this.SendPropertyChanging();
					this._ROWORDER = value;
					this.SendPropertyChanged("ROWORDER");
					this.OnROWORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMTAXTYPE", DbType="SmallInt NOT NULL")]
		public short ITEMTAXTYPE
		{
			get
			{
				return this._ITEMTAXTYPE;
			}
			set
			{
				if ((this._ITEMTAXTYPE != value))
				{
					this.OnITEMTAXTYPEChanging(value);
					this.SendPropertyChanging();
					this._ITEMTAXTYPE = value;
					this.SendPropertyChanged("ITEMTAXTYPE");
					this.OnITEMTAXTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTCODE", DbType="VarChar(20)")]
		public string PRODUCTCODE
		{
			get
			{
				return this._PRODUCTCODE;
			}
			set
			{
				if ((this._PRODUCTCODE != value))
				{
					this.OnPRODUCTCODEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTCODE = value;
					this.SendPropertyChanged("PRODUCTCODE");
					this.OnPRODUCTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTNAME", DbType="VarChar(250)")]
		public string PRODUCTNAME
		{
			get
			{
				return this._PRODUCTNAME;
			}
			set
			{
				if ((this._PRODUCTNAME != value))
				{
					this.OnPRODUCTNAMEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTNAME = value;
					this.SendPropertyChanged("PRODUCTNAME");
					this.OnPRODUCTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARCODE", DbType="VarChar(20)")]
		public string BARCODE
		{
			get
			{
				return this._BARCODE;
			}
			set
			{
				if ((this._BARCODE != value))
				{
					this.OnBARCODEChanging(value);
					this.SendPropertyChanging();
					this._BARCODE = value;
					this.SendPropertyChanged("BARCODE");
					this.OnBARCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITECODE", DbType="VarChar(20)")]
		public string SITECODE
		{
			get
			{
				return this._SITECODE;
			}
			set
			{
				if ((this._SITECODE != value))
				{
					this.OnSITECODEChanging(value);
					this.SendPropertyChanging();
					this._SITECODE = value;
					this.SendPropertyChanged("SITECODE");
					this.OnSITECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLOC", DbType="VarChar(20)")]
		public string SLOC
		{
			get
			{
				return this._SLOC;
			}
			set
			{
				if ((this._SLOC != value))
				{
					this.OnSLOCChanging(value);
					this.SendPropertyChanging();
					this._SLOC = value;
					this.SendPropertyChanged("SLOC");
					this.OnSLOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="VarChar(20)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this.OnLOCATIONChanging(value);
					this.SendPropertyChanging();
					this._LOCATION = value;
					this.SendPropertyChanged("LOCATION");
					this.OnLOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITCODE", DbType="VarChar(20)")]
		public string UNITCODE
		{
			get
			{
				return this._UNITCODE;
			}
			set
			{
				if ((this._UNITCODE != value))
				{
					this.OnUNITCODEChanging(value);
					this.SendPropertyChanging();
					this._UNITCODE = value;
					this.SendPropertyChanged("UNITCODE");
					this.OnUNITCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITRATE", DbType="Money NOT NULL")]
		public decimal UNITRATE
		{
			get
			{
				return this._UNITRATE;
			}
			set
			{
				if ((this._UNITRATE != value))
				{
					this.OnUNITRATEChanging(value);
					this.SendPropertyChanging();
					this._UNITRATE = value;
					this.SendPropertyChanged("UNITRATE");
					this.OnUNITRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Money NOT NULL")]
		public decimal QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMAINQTY", DbType="Money NOT NULL")]
		public decimal REMAINQTY
		{
			get
			{
				return this._REMAINQTY;
			}
			set
			{
				if ((this._REMAINQTY != value))
				{
					this.OnREMAINQTYChanging(value);
					this.SendPropertyChanging();
					this._REMAINQTY = value;
					this.SendPropertyChanged("REMAINQTY");
					this.OnREMAINQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STDUNITPRICE", DbType="Money NOT NULL")]
		public decimal STDUNITPRICE
		{
			get
			{
				return this._STDUNITPRICE;
			}
			set
			{
				if ((this._STDUNITPRICE != value))
				{
					this.OnSTDUNITPRICEChanging(value);
					this.SendPropertyChanging();
					this._STDUNITPRICE = value;
					this.SendPropertyChanged("STDUNITPRICE");
					this.OnSTDUNITPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXVALUE", DbType="Money NOT NULL")]
		public decimal TAXVALUE
		{
			get
			{
				return this._TAXVALUE;
			}
			set
			{
				if ((this._TAXVALUE != value))
				{
					this.OnTAXVALUEChanging(value);
					this.SendPropertyChanging();
					this._TAXVALUE = value;
					this.SendPropertyChanged("TAXVALUE");
					this.OnTAXVALUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITPRICEBEFORETAX", DbType="Money NOT NULL")]
		public decimal UNITPRICEBEFORETAX
		{
			get
			{
				return this._UNITPRICEBEFORETAX;
			}
			set
			{
				if ((this._UNITPRICEBEFORETAX != value))
				{
					this.OnUNITPRICEBEFORETAXChanging(value);
					this.SendPropertyChanging();
					this._UNITPRICEBEFORETAX = value;
					this.SendPropertyChanged("UNITPRICEBEFORETAX");
					this.OnUNITPRICEBEFORETAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITPRICE", DbType="Money NOT NULL")]
		public decimal UNITPRICE
		{
			get
			{
				return this._UNITPRICE;
			}
			set
			{
				if ((this._UNITPRICE != value))
				{
					this.OnUNITPRICEChanging(value);
					this.SendPropertyChanging();
					this._UNITPRICE = value;
					this.SendPropertyChanged("UNITPRICE");
					this.OnUNITPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITPRICE_BEFORE_ADD", DbType="Money")]
		public System.Nullable<decimal> UNITPRICE_BEFORE_ADD
		{
			get
			{
				return this._UNITPRICE_BEFORE_ADD;
			}
			set
			{
				if ((this._UNITPRICE_BEFORE_ADD != value))
				{
					this.OnUNITPRICE_BEFORE_ADDChanging(value);
					this.SendPropertyChanging();
					this._UNITPRICE_BEFORE_ADD = value;
					this.SendPropertyChanged("UNITPRICE_BEFORE_ADD");
					this.OnUNITPRICE_BEFORE_ADDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NETAMOUNT", DbType="Money NOT NULL")]
		public decimal NETAMOUNT
		{
			get
			{
				return this._NETAMOUNT;
			}
			set
			{
				if ((this._NETAMOUNT != value))
				{
					this.OnNETAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._NETAMOUNT = value;
					this.SendPropertyChanged("NETAMOUNT");
					this.OnNETAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALECODE", DbType="VarChar(20)")]
		public string SALECODE
		{
			get
			{
				return this._SALECODE;
			}
			set
			{
				if ((this._SALECODE != value))
				{
					this.OnSALECODEChanging(value);
					this.SendPropertyChanging();
					this._SALECODE = value;
					this.SendPropertyChanged("SALECODE");
					this.OnSALECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCCODE", DbType="VarChar(20)")]
		public string PCCODE
		{
			get
			{
				return this._PCCODE;
			}
			set
			{
				if ((this._PCCODE != value))
				{
					this.OnPCCODEChanging(value);
					this.SendPropertyChanging();
					this._PCCODE = value;
					this.SendPropertyChanged("PCCODE");
					this.OnPCCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARK", DbType="VarChar(250)")]
		public string REMARK
		{
			get
			{
				return this._REMARK;
			}
			set
			{
				if ((this._REMARK != value))
				{
					this.OnREMARKChanging(value);
					this.SendPropertyChanging();
					this._REMARK = value;
					this.SendPropertyChanged("REMARK");
					this.OnREMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANCELFLAG", DbType="SmallInt NOT NULL")]
		public short CANCELFLAG
		{
			get
			{
				return this._CANCELFLAG;
			}
			set
			{
				if ((this._CANCELFLAG != value))
				{
					this.OnCANCELFLAGChanging(value);
					this.SendPropertyChanging();
					this._CANCELFLAG = value;
					this.SendPropertyChanged("CANCELFLAG");
					this.OnCANCELFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANCELREASON", DbType="VarChar(20)")]
		public string CANCELREASON
		{
			get
			{
				return this._CANCELREASON;
			}
			set
			{
				if ((this._CANCELREASON != value))
				{
					this.OnCANCELREASONChanging(value);
					this.SendPropertyChanging();
					this._CANCELREASON = value;
					this.SendPropertyChanged("CANCELREASON");
					this.OnCANCELREASONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERCODEAPPROVE", DbType="VarChar(20)")]
		public string USERCODEAPPROVE
		{
			get
			{
				return this._USERCODEAPPROVE;
			}
			set
			{
				if ((this._USERCODEAPPROVE != value))
				{
					this.OnUSERCODEAPPROVEChanging(value);
					this.SendPropertyChanging();
					this._USERCODEAPPROVE = value;
					this.SendPropertyChanged("USERCODEAPPROVE");
					this.OnUSERCODEAPPROVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXPORTFLAG", DbType="SmallInt NOT NULL")]
		public short EXPORTFLAG
		{
			get
			{
				return this._EXPORTFLAG;
			}
			set
			{
				if ((this._EXPORTFLAG != value))
				{
					this.OnEXPORTFLAGChanging(value);
					this.SendPropertyChanging();
					this._EXPORTFLAG = value;
					this.SendPropertyChanged("EXPORTFLAG");
					this.OnEXPORTFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPDOCNO", DbType="VarChar(20)")]
		public string SAPDOCNO
		{
			get
			{
				return this._SAPDOCNO;
			}
			set
			{
				if ((this._SAPDOCNO != value))
				{
					this.OnSAPDOCNOChanging(value);
					this.SendPropertyChanging();
					this._SAPDOCNO = value;
					this.SendPropertyChanged("SAPDOCNO");
					this.OnSAPDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPREFDOCNO", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SAPREFDOCNO
		{
			get
			{
				return this._SAPREFDOCNO;
			}
			set
			{
				if ((this._SAPREFDOCNO != value))
				{
					this.OnSAPREFDOCNOChanging(value);
					this.SendPropertyChanging();
					this._SAPREFDOCNO = value;
					this.SendPropertyChanged("SAPREFDOCNO");
					this.OnSAPREFDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCKEXPORTFLAG", DbType="SmallInt NOT NULL")]
		public short STOCKEXPORTFLAG
		{
			get
			{
				return this._STOCKEXPORTFLAG;
			}
			set
			{
				if ((this._STOCKEXPORTFLAG != value))
				{
					this.OnSTOCKEXPORTFLAGChanging(value);
					this.SendPropertyChanging();
					this._STOCKEXPORTFLAG = value;
					this.SendPropertyChanged("STOCKEXPORTFLAG");
					this.OnSTOCKEXPORTFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPSTOCKDOCNO", DbType="VarChar(20)")]
		public string SAPSTOCKDOCNO
		{
			get
			{
				return this._SAPSTOCKDOCNO;
			}
			set
			{
				if ((this._SAPSTOCKDOCNO != value))
				{
					this.OnSAPSTOCKDOCNOChanging(value);
					this.SendPropertyChanging();
					this._SAPSTOCKDOCNO = value;
					this.SendPropertyChanged("SAPSTOCKDOCNO");
					this.OnSAPSTOCKDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATERIALTYPE", DbType="SmallInt NOT NULL")]
		public short MATERIALTYPE
		{
			get
			{
				return this._MATERIALTYPE;
			}
			set
			{
				if ((this._MATERIALTYPE != value))
				{
					this.OnMATERIALTYPEChanging(value);
					this.SendPropertyChanging();
					this._MATERIALTYPE = value;
					this.SendPropertyChanged("MATERIALTYPE");
					this.OnMATERIALTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALEROWORDER", DbType="SmallInt NOT NULL")]
		public short SALEROWORDER
		{
			get
			{
				return this._SALEROWORDER;
			}
			set
			{
				if ((this._SALEROWORDER != value))
				{
					this.OnSALEROWORDERChanging(value);
					this.SendPropertyChanging();
					this._SALEROWORDER = value;
					this.SendPropertyChanged("SALEROWORDER");
					this.OnSALEROWORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANCELROWORDER", DbType="SmallInt NOT NULL")]
		public short CANCELROWORDER
		{
			get
			{
				return this._CANCELROWORDER;
			}
			set
			{
				if ((this._CANCELROWORDER != value))
				{
					this.OnCANCELROWORDERChanging(value);
					this.SendPropertyChanging();
					this._CANCELROWORDER = value;
					this.SendPropertyChanged("CANCELROWORDER");
					this.OnCANCELROWORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MTPOS", DbType="VarChar(20)")]
		public string MTPOS
		{
			get
			{
				return this._MTPOS;
			}
			set
			{
				if ((this._MTPOS != value))
				{
					this.OnMTPOSChanging(value);
					this.SendPropertyChanging();
					this._MTPOS = value;
					this.SendPropertyChanged("MTPOS");
					this.OnMTPOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITPRICECALVAT", DbType="Money NOT NULL")]
		public decimal UNITPRICECALVAT
		{
			get
			{
				return this._UNITPRICECALVAT;
			}
			set
			{
				if ((this._UNITPRICECALVAT != value))
				{
					this.OnUNITPRICECALVATChanging(value);
					this.SendPropertyChanging();
					this._UNITPRICECALVAT = value;
					this.SendPropertyChanged("UNITPRICECALVAT");
					this.OnUNITPRICECALVATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NETAMOUNTCALVAT", DbType="Money NOT NULL")]
		public decimal NETAMOUNTCALVAT
		{
			get
			{
				return this._NETAMOUNTCALVAT;
			}
			set
			{
				if ((this._NETAMOUNTCALVAT != value))
				{
					this.OnNETAMOUNTCALVATChanging(value);
					this.SendPropertyChanging();
					this._NETAMOUNTCALVAT = value;
					this.SendPropertyChanged("NETAMOUNTCALVAT");
					this.OnNETAMOUNTCALVATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRCHARGEFLAG", DbType="SmallInt NOT NULL")]
		public short CRCHARGEFLAG
		{
			get
			{
				return this._CRCHARGEFLAG;
			}
			set
			{
				if ((this._CRCHARGEFLAG != value))
				{
					this.OnCRCHARGEFLAGChanging(value);
					this.SendPropertyChanging();
					this._CRCHARGEFLAG = value;
					this.SendPropertyChanged("CRCHARGEFLAG");
					this.OnCRCHARGEFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALECOLORDOCNO", DbType="VarChar(20)")]
		public string SALECOLORDOCNO
		{
			get
			{
				return this._SALECOLORDOCNO;
			}
			set
			{
				if ((this._SALECOLORDOCNO != value))
				{
					this.OnSALECOLORDOCNOChanging(value);
					this.SendPropertyChanging();
					this._SALECOLORDOCNO = value;
					this.SendPropertyChanged("SALECOLORDOCNO");
					this.OnSALECOLORDOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALECOLORFORMULANAME", DbType="VarChar(150)")]
		public string SALECOLORFORMULANAME
		{
			get
			{
				return this._SALECOLORFORMULANAME;
			}
			set
			{
				if ((this._SALECOLORFORMULANAME != value))
				{
					this.OnSALECOLORFORMULANAMEChanging(value);
					this.SendPropertyChanging();
					this._SALECOLORFORMULANAME = value;
					this.SendPropertyChanged("SALECOLORFORMULANAME");
					this.OnSALECOLORFORMULANAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALECOLORFORMULASALEQTY", DbType="Money NOT NULL")]
		public decimal SALECOLORFORMULASALEQTY
		{
			get
			{
				return this._SALECOLORFORMULASALEQTY;
			}
			set
			{
				if ((this._SALECOLORFORMULASALEQTY != value))
				{
					this.OnSALECOLORFORMULASALEQTYChanging(value);
					this.SendPropertyChanging();
					this._SALECOLORFORMULASALEQTY = value;
					this.SendPropertyChanged("SALECOLORFORMULASALEQTY");
					this.OnSALECOLORFORMULASALEQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALECOLORROWORDER", DbType="SmallInt NOT NULL")]
		public short SALECOLORROWORDER
		{
			get
			{
				return this._SALECOLORROWORDER;
			}
			set
			{
				if ((this._SALECOLORROWORDER != value))
				{
					this.OnSALECOLORROWORDERChanging(value);
					this.SendPropertyChanging();
					this._SALECOLORROWORDER = value;
					this.SendPropertyChanged("SALECOLORROWORDER");
					this.OnSALECOLORROWORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSDOCFLAG", DbType="SmallInt")]
		public System.Nullable<short> SYSDOCFLAG
		{
			get
			{
				return this._SYSDOCFLAG;
			}
			set
			{
				if ((this._SYSDOCFLAG != value))
				{
					this.OnSYSDOCFLAGChanging(value);
					this.SendPropertyChanging();
					this._SYSDOCFLAG = value;
					this.SendPropertyChanged("SYSDOCFLAG");
					this.OnSYSDOCFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZO02PERCENT", DbType="Money NOT NULL")]
		public decimal ZO02PERCENT
		{
			get
			{
				return this._ZO02PERCENT;
			}
			set
			{
				if ((this._ZO02PERCENT != value))
				{
					this.OnZO02PERCENTChanging(value);
					this.SendPropertyChanging();
					this._ZO02PERCENT = value;
					this.SendPropertyChanged("ZO02PERCENT");
					this.OnZO02PERCENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZO02VALUE", DbType="Money NOT NULL")]
		public decimal ZO02VALUE
		{
			get
			{
				return this._ZO02VALUE;
			}
			set
			{
				if ((this._ZO02VALUE != value))
				{
					this.OnZO02VALUEChanging(value);
					this.SendPropertyChanging();
					this._ZO02VALUE = value;
					this.SendPropertyChanged("ZO02VALUE");
					this.OnZO02VALUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITPRICEOLD", DbType="Money NOT NULL")]
		public decimal UNITPRICEOLD
		{
			get
			{
				return this._UNITPRICEOLD;
			}
			set
			{
				if ((this._UNITPRICEOLD != value))
				{
					this.OnUNITPRICEOLDChanging(value);
					this.SendPropertyChanging();
					this._UNITPRICEOLD = value;
					this.SendPropertyChanged("UNITPRICEOLD");
					this.OnUNITPRICEOLDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISPROMOTIONPRICE", DbType="SmallInt NOT NULL")]
		public short ISPROMOTIONPRICE
		{
			get
			{
				return this._ISPROMOTIONPRICE;
			}
			set
			{
				if ((this._ISPROMOTIONPRICE != value))
				{
					this.OnISPROMOTIONPRICEChanging(value);
					this.SendPropertyChanging();
					this._ISPROMOTIONPRICE = value;
					this.SendPropertyChanged("ISPROMOTIONPRICE");
					this.OnISPROMOTIONPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITPRICECALVATOLD", DbType="Money NOT NULL")]
		public decimal UNITPRICECALVATOLD
		{
			get
			{
				return this._UNITPRICECALVATOLD;
			}
			set
			{
				if ((this._UNITPRICECALVATOLD != value))
				{
					this.OnUNITPRICECALVATOLDChanging(value);
					this.SendPropertyChanging();
					this._UNITPRICECALVATOLD = value;
					this.SendPropertyChanged("UNITPRICECALVATOLD");
					this.OnUNITPRICECALVATOLDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITPRICECHARGE", DbType="Money NOT NULL")]
		public decimal UNITPRICECHARGE
		{
			get
			{
				return this._UNITPRICECHARGE;
			}
			set
			{
				if ((this._UNITPRICECHARGE != value))
				{
					this.OnUNITPRICECHARGEChanging(value);
					this.SendPropertyChanging();
					this._UNITPRICECHARGE = value;
					this.SendPropertyChanged("UNITPRICECHARGE");
					this.OnUNITPRICECHARGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITPRICEWT", DbType="Money NOT NULL")]
		public decimal UNITPRICEWT
		{
			get
			{
				return this._UNITPRICEWT;
			}
			set
			{
				if ((this._UNITPRICEWT != value))
				{
					this.OnUNITPRICEWTChanging(value);
					this.SendPropertyChanging();
					this._UNITPRICEWT = value;
					this.SendPropertyChanged("UNITPRICEWT");
					this.OnUNITPRICEWTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITPRICEWT_CUS", DbType="Money NOT NULL")]
		public decimal UNITPRICEWT_CUS
		{
			get
			{
				return this._UNITPRICEWT_CUS;
			}
			set
			{
				if ((this._UNITPRICEWT_CUS != value))
				{
					this.OnUNITPRICEWT_CUSChanging(value);
					this.SendPropertyChanging();
					this._UNITPRICEWT_CUS = value;
					this.SendPropertyChanged("UNITPRICEWT_CUS");
					this.OnUNITPRICEWT_CUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITPRICEWT_UW", DbType="Money NOT NULL")]
		public decimal UNITPRICEWT_UW
		{
			get
			{
				return this._UNITPRICEWT_UW;
			}
			set
			{
				if ((this._UNITPRICEWT_UW != value))
				{
					this.OnUNITPRICEWT_UWChanging(value);
					this.SendPropertyChanging();
					this._UNITPRICEWT_UW = value;
					this.SendPropertyChanged("UNITPRICEWT_UW");
					this.OnUNITPRICEWT_UWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NETAMOUNTWT_CUS", DbType="Money NOT NULL")]
		public decimal NETAMOUNTWT_CUS
		{
			get
			{
				return this._NETAMOUNTWT_CUS;
			}
			set
			{
				if ((this._NETAMOUNTWT_CUS != value))
				{
					this.OnNETAMOUNTWT_CUSChanging(value);
					this.SendPropertyChanging();
					this._NETAMOUNTWT_CUS = value;
					this.SendPropertyChanged("NETAMOUNTWT_CUS");
					this.OnNETAMOUNTWT_CUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NETAMOUNTWT_UW", DbType="Money NOT NULL")]
		public decimal NETAMOUNTWT_UW
		{
			get
			{
				return this._NETAMOUNTWT_UW;
			}
			set
			{
				if ((this._NETAMOUNTWT_UW != value))
				{
					this.OnNETAMOUNTWT_UWChanging(value);
					this.SendPropertyChanging();
					this._NETAMOUNTWT_UW = value;
					this.SendPropertyChanged("NETAMOUNTWT_UW");
					this.OnNETAMOUNTWT_UWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROMOTION_NUMBER", DbType="VarChar(50)")]
		public string PROMOTION_NUMBER
		{
			get
			{
				return this._PROMOTION_NUMBER;
			}
			set
			{
				if ((this._PROMOTION_NUMBER != value))
				{
					this.OnPROMOTION_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._PROMOTION_NUMBER = value;
					this.SendPropertyChanged("PROMOTION_NUMBER");
					this.OnPROMOTION_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BONUSBUY_ID", DbType="VarChar(50)")]
		public string BONUSBUY_ID
		{
			get
			{
				return this._BONUSBUY_ID;
			}
			set
			{
				if ((this._BONUSBUY_ID != value))
				{
					this.OnBONUSBUY_IDChanging(value);
					this.SendPropertyChanging();
					this._BONUSBUY_ID = value;
					this.SendPropertyChanged("BONUSBUY_ID");
					this.OnBONUSBUY_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROMOTION_PRICE_NO", DbType="VarChar(50)")]
		public string PROMOTION_PRICE_NO
		{
			get
			{
				return this._PROMOTION_PRICE_NO;
			}
			set
			{
				if ((this._PROMOTION_PRICE_NO != value))
				{
					this.OnPROMOTION_PRICE_NOChanging(value);
					this.SendPropertyChanging();
					this._PROMOTION_PRICE_NO = value;
					this.SendPropertyChanged("PROMOTION_PRICE_NO");
					this.OnPROMOTION_PRICE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROMOTION_PRICE_ROWORDER", DbType="Int")]
		public System.Nullable<int> PROMOTION_PRICE_ROWORDER
		{
			get
			{
				return this._PROMOTION_PRICE_ROWORDER;
			}
			set
			{
				if ((this._PROMOTION_PRICE_ROWORDER != value))
				{
					this.OnPROMOTION_PRICE_ROWORDERChanging(value);
					this.SendPropertyChanging();
					this._PROMOTION_PRICE_ROWORDER = value;
					this.SendPropertyChanged("PROMOTION_PRICE_ROWORDER");
					this.OnPROMOTION_PRICE_ROWORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNT", DbType="Money NOT NULL")]
		public decimal DISCOUNT
		{
			get
			{
				return this._DISCOUNT;
			}
			set
			{
				if ((this._DISCOUNT != value))
				{
					this.OnDISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._DISCOUNT = value;
					this.SendPropertyChanged("DISCOUNT");
					this.OnDISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAX_AFTER_DISCOUNT", DbType="Money")]
		public System.Nullable<decimal> TAX_AFTER_DISCOUNT
		{
			get
			{
				return this._TAX_AFTER_DISCOUNT;
			}
			set
			{
				if ((this._TAX_AFTER_DISCOUNT != value))
				{
					this.OnTAX_AFTER_DISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._TAX_AFTER_DISCOUNT = value;
					this.SendPropertyChanged("TAX_AFTER_DISCOUNT");
					this.OnTAX_AFTER_DISCOUNTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
